### ISSUE TITLE
next and previous link to firebasapp

### ISSUE THREAD

**Issue by Naramsim** [PokeAPI/deploy#4]
By querying https://pokeapi.co/api/v2/pokemon?offset=1&limit=3, we get this result.

```json
{
  count: 949,
  next: "https://pokeapi-215911.firebaseapp.com/api/v2/pokemon?offset=4&limit=3",
  previous: "https://pokeapi-215911.firebaseapp.com/api/v2/pokemon?offset=0&limit=1",
...
```

**Comment by Naramsim** [comment]
We should update this line: https://github.com/PokeAPI/deploy/blob/master/functions/src/index.ts#L9

**Comment by tdmalone** [comment]
^ Ideally that line should be provided by an environment variable, rather than being hard coded.

Firebase may already provide a suitable variable; if not hopefully we can create one.
